export const countryAlpha3IsoCodes = [
    'AND',
    'ARE',
    'AFG',
    'ATG',
    'AIA',
    'ALB',
    'ARM',
    'AGO',
    'ATA',
    'ARG',
    'ASM',
    'AUT',
    'AUS',
    'ABW',
    'ALA',
    'AZE',
    'BIH',
    'BRB',
    'BGD',
    'BEL',
    'BFA',
    'BGR',
    'BHR',
    'BDI',
    'BEN',
    'BLM',
    'BMU',
    'BRN',
    'BOL',
    'BES',
    'BRA',
    'BHS',
    'BTN',
    'BVT',
    'BWA',
    'BLR',
    'BLZ',
    'CAN',
    'CCK',
    'COD',
    'CAF',
    'COG',
    'CHE',
    'CIV',
    'COK',
    'CHL',
    'CMR',
    'CHN',
    'COL',
    'CRI',
    'CUB',
    'CPV',
    'CUW',
    'CXR',
    'CYP',
    'CZE',
    'DEU',
    'DJI',
    'DNK',
    'DMA',
    'DOM',
    'DZA',
    'ECU',
    'EST',
    'EGY',
    'ESH',
    'ERI',
    'ESP',
    'ETH',
    'FIN',
    'FJI',
    'FLK',
    'FSM',
    'FRO',
    'FRA',
    'GAB',
    'GBR',
    'GRD',
    'GEO',
    'GUF',
    'GGY',
    'GHA',
    'GIB',
    'GRL',
    'GMB',
    'GIN',
    'GLP',
    'GNQ',
    'GRC',
    'SGS',
    'GTM',
    'GUM',
    'GNB',
    'GUY',
    'HKG',
    'HMD',
    'HND',
    'HRV',
    'HTI',
    'HUN',
    'IDN',
    'IRL',
    'ISR',
    'IMN',
    'IND',
    'IOT',
    'IRQ',
    'IRN',
    'ISL',
    'ITA',
    'JEY',
    'JAM',
    'JOR',
    'JPN',
    'KEN',
    'KGZ',
    'KHM',
    'KIR',
    'COM',
    'KNA',
    'PRK',
    'KOR',
    'KWT',
    'CYM',
    'KAZ',
    'LAO',
    'LBN',
    'LCA',
    'LIE',
    'LKA',
    'LBR',
    'LSO',
    'LTU',
    'LUX',
    'LVA',
    'LBY',
    'MAR',
    'MCO',
    'MDA',
    'MNE',
    'MAF',
    'MDG',
    'MHL',
    'MKD',
    'MLI',
    'MMR',
    'MNG',
    'MAC',
    'MNP',
    'MTQ',
    'MRT',
    'MSR',
    'MLT',
    'MUS',
    'MDV',
    'MWI',
    'MEX',
    'MYS',
    'MOZ',
    'NAM',
    'NCL',
    'NER',
    'NFK',
    'NGA',
    'NIC',
    'NLD',
    'NOR',
    'NPL',
    'NRU',
    'NIU',
    'NZL',
    'OMN',
    'PAN',
    'PER',
    'PYF',
    'PNG',
    'PHL',
    'PAK',
    'POL',
    'SPM',
    'PCN',
    'PRI',
    'PSE',
    'PRT',
    'PLW',
    'PRY',
    'QAT',
    'REU',
    'ROU',
    'SRB',
    'RUS',
    'RWA',
    'SAU',
    'SLB',
    'SYC',
    'SDN',
    'SWE',
    'SGP',
    'SHN',
    'SVN',
    'SJM',
    'SVK',
    'SLE',
    'SMR',
    'SEN',
    'SOM',
    'SUR',
    'SSD',
    'STP',
    'SLV',
    'SXM',
    'SYR',
    'SWZ',
    'TCA',
    'TCD',
    'ATF',
    'TGO',
    'THA',
    'TJK',
    'TKL',
    'TLS',
    'TKM',
    'TUN',
    'TON',
    'TUR',
    'TTO',
    'TUV',
    'TWN',
    'TZA',
    'UKR',
    'UGA',
    'UMI',
    'USA',
    'URY',
    'UZB',
    'VAT',
    'VCT',
    'VEN',
    'VGB',
    'VIR',
    'VNM',
    'VUT',
    'WLF',
    'WSM',
    'YEM',
    'MYT',
    'ZAF',
    'ZMB',
    'ZWE',
] as const;

export const countryAlpha2IsoCodes = [
    'AF',
    'AL',
    'DZ',
    'AS',
    'AD',
    'AO',
    'AI',
    'AQ',
    'AG',
    'AR',
    'AM',
    'AW',
    'AU',
    'AT',
    'AZ',
    'BS',
    'BH',
    'BD',
    'BB',
    'BY',
    'BE',
    'BZ',
    'BJ',
    'BM',
    'BT',
    'BO',
    'BQ',
    'BA',
    'BW',
    'BV',
    'BR',
    'IO',
    'BN',
    'BG',
    'BF',
    'BI',
    'CV',
    'KH',
    'CM',
    'CA',
    'KY',
    'CF',
    'TD',
    'CL',
    'CN',
    'CX',
    'CC',
    'CO',
    'KM',
    'CD',
    'CG',
    'CK',
    'CR',
    'HR',
    'CU',
    'CW',
    'CY',
    'CZ',
    'CI',
    'DK',
    'DJ',
    'DM',
    'DO',
    'EC',
    'EG',
    'SV',
    'GQ',
    'ER',
    'EE',
    'SZ',
    'ET',
    'FK',
    'FO',
    'FJ',
    'FI',
    'FR',
    'GF',
    'PF',
    'TF',
    'GA',
    'GM',
    'GE',
    'DE',
    'GH',
    'GI',
    'GR',
    'GL',
    'GD',
    'GP',
    'GU',
    'GT',
    'GG',
    'GN',
    'GW',
    'GY',
    'HT',
    'HM',
    'VA',
    'HN',
    'HK',
    'HU',
    'IS',
    'IN',
    'ID',
    'IR',
    'IQ',
    'IE',
    'IM',
    'IL',
    'IT',
    'JM',
    'JP',
    'JE',
    'JO',
    'KZ',
    'KE',
    'KI',
    'KP',
    'KR',
    'KW',
    'KG',
    'LA',
    'LV',
    'LB',
    'LS',
    'LR',
    'LY',
    'LI',
    'LT',
    'LU',
    'MO',
    'MG',
    'MW',
    'MY',
    'MV',
    'ML',
    'MT',
    'MH',
    'MQ',
    'MR',
    'MU',
    'YT',
    'MX',
    'FM',
    'MD',
    'MC',
    'MN',
    'ME',
    'MS',
    'MA',
    'MZ',
    'MM',
    'NA',
    'NR',
    'NP',
    'NL',
    'NC',
    'NZ',
    'NI',
    'NE',
    'NG',
    'NU',
    'NF',
    'MP',
    'NO',
    'OM',
    'PK',
    'PW',
    'PS',
    'PA',
    'PG',
    'PY',
    'PE',
    'PH',
    'PN',
    'PL',
    'PT',
    'PR',
    'QA',
    'MK',
    'RO',
    'RU',
    'RW',
    'RE',
    'BL',
    'SH',
    'KN',
    'LC',
    'MF',
    'PM',
    'VC',
    'WS',
    'SM',
    'ST',
    'SA',
    'SN',
    'RS',
    'SC',
    'SL',
    'SG',
    'SX',
    'SK',
    'SI',
    'SB',
    'SO',
    'ZA',
    'GS',
    'SS',
    'ES',
    'LK',
    'SD',
    'SR',
    'SJ',
    'SE',
    'CH',
    'SY',
    'TW',
    'TJ',
    'TZ',
    'TH',
    'TL',
    'TG',
    'TK',
    'TO',
    'TT',
    'TN',
    'TR',
    'TM',
    'TC',
    'TV',
    'UG',
    'UA',
    'AE',
    'GB',
    'UM',
    'US',
    'UK',
    'UY',
    'UZ',
    'VU',
    'VE',
    'VN',
    'VG',
    'VI',
    'WF',
    'EH',
    'YE',
    'ZM',
    'ZW',
    'AX',
] as const;

export const isoCodeMapping = {
    AF: {
        isoAlpha3: 'AFG',
        diallingCode: '93',
        country: 'Afghanistan',
        timeZone: 'Asia/Kabul',
        currencyCode: 'AFN',
        currencyNumber: '971',
        locale: 'ps-AF',
    },
    AX: {
        isoAlpha3: 'ALA',
        diallingCode: '358',
        country: 'Åland Islands',
        timeZone: 'Europe/Mariehamn',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'sv-AX',
    },
    AL: {
        isoAlpha3: 'ALB',
        diallingCode: '355',
        country: 'Albania',
        timeZone: 'Europe/Tirane',
        currencyCode: 'ALL',
        currencyNumber: '008',
        locale: 'sq-AL',
    },
    DZ: {
        isoAlpha3: 'DZA',
        diallingCode: '213',
        country: 'Algeria',
        timeZone: 'Africa/Algiers',
        currencyCode: 'DZD',
        currencyNumber: '012',
        locale: 'ar-DZ',
    },
    AS: {
        isoAlpha3: 'ASM',
        diallingCode: '1-684',
        country: 'American Samoa',
        timeZone: 'Pacific/Pago_Pago',
        currencyCode: 'USD',
        currencyNumber: '840',
        locale: 'en-AS',
    },
    AD: {
        isoAlpha3: 'AND',
        diallingCode: '376',
        country: 'Andorra',
        timeZone: 'Europe/Andorra',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'ca-AD',
    },
    AO: {
        isoAlpha3: 'AGO',
        diallingCode: '244',
        country: 'Angola',
        timeZone: 'Africa/Luanda',
        currencyCode: 'AOA',
        currencyNumber: '973',
        locale: 'pt-AO',
    },
    AI: {
        isoAlpha3: 'AIA',
        diallingCode: '1-264',
        country: 'Anguilla',
        timeZone: 'America/Anguilla',
        currencyCode: 'XCD',
        currencyNumber: '951',
        locale: 'en-AI',
    },
    AQ: {
        isoAlpha3: 'ATA',
        diallingCode: '672',
        country: 'Antarctica',
        timeZone: 'Antarctica/Casey',
        locale: '',
    },
    AG: {
        isoAlpha3: 'ATG',
        diallingCode: '1-268',
        country: 'Antigua and Barbuda',
        timeZone: 'America/Antigua',
        currencyCode: 'XCD',
        currencyNumber: '951',
        locale: 'en-AG',
    },
    AR: {
        isoAlpha3: 'ARG',
        diallingCode: '54',
        country: 'Argentina',
        timeZone: 'America/Argentina/Buenos_Aires',
        currencyCode: 'ARS',
        currencyNumber: '032',
        locale: 'es-AR',
    },
    AM: {
        isoAlpha3: 'ARM',
        diallingCode: '374',
        country: 'Armenia',
        timeZone: 'Asia/Yerevan',
        currencyCode: 'AMD',
        currencyNumber: '051',
        locale: 'hy-AM',
    },
    AW: {
        isoAlpha3: 'ABW',
        diallingCode: '297',
        country: 'Aruba',
        timeZone: 'America/Aruba',
        currencyCode: 'AWG',
        currencyNumber: '533',
        locale: 'nl-AW',
    },
    AU: {
        isoAlpha3: 'AUS',
        diallingCode: '61',
        country: 'Australia',
        timeZone: 'Antarctica/Macquarie',
        currencyCode: 'AUD',
        currencyNumber: '036',
        locale: 'en-AU',
    },
    AT: {
        isoAlpha3: 'AUT',
        diallingCode: '43',
        country: 'Austria',
        timeZone: 'Europe/Vienna',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'de-AT',
    },
    AZ: {
        isoAlpha3: 'AZE',
        diallingCode: '994',
        country: 'Azerbaijan',
        timeZone: 'Asia/Baku',
        currencyCode: 'AZN',
        currencyNumber: '944',
        locale: 'az-AZ',
    },
    BS: {
        isoAlpha3: 'BHS',
        diallingCode: '1-242',

        country: 'Bahamas',
        timeZone: 'America/Nassau',
        currencyCode: 'BSD',
        currencyNumber: '044',
        locale: 'en-BS',
    },
    BH: {
        isoAlpha3: 'BHR',
        diallingCode: '973',
        country: 'Bahrain',
        timeZone: 'Asia/Bahrain',
        currencyCode: 'BHD',
        currencyNumber: '048',
        locale: 'ar-BH',
    },
    BD: {
        isoAlpha3: 'BGD',
        diallingCode: '880',
        country: 'Bangladesh',
        timeZone: 'Asia/Dhaka',
        currencyCode: 'BDT',
        currencyNumber: '050',
        locale: 'bn-BD',
    },
    BB: {
        isoAlpha3: 'BRB',
        diallingCode: '1-246',
        country: 'Barbados',
        timeZone: 'America/Barbados',
        currencyCode: 'BBD',
        currencyNumber: '052',
        locale: 'en-BB',
    },
    BY: {
        isoAlpha3: 'BLR',
        diallingCode: '375',
        country: 'Belarus',
        timeZone: 'Europe/Minsk',
        currencyCode: 'BYN',
        currencyNumber: '933',
        locale: 'be-BY',
    },
    BE: {
        isoAlpha3: 'BEL',
        diallingCode: '32',
        country: 'Belgium',
        timeZone: 'Europe/Brussels',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'nl-BE',
    },
    BZ: {
        isoAlpha3: 'BLZ',
        diallingCode: '501',
        country: 'Belize',
        timeZone: 'America/Belize',
        currencyCode: 'BZD',
        currencyNumber: '084',
        locale: 'en-BZ',
    },
    BJ: {
        isoAlpha3: 'BEN',
        diallingCode: '229',
        country: 'Benin',
        timeZone: 'Africa/Porto-Novo',
        currencyCode: 'XOF',
        currencyNumber: '952',
        locale: 'fr-BJ',
    },
    BM: {
        isoAlpha3: 'BMU',
        diallingCode: '1-441',
        country: 'Bermuda',
        timeZone: 'Atlantic/Bermuda',
        currencyCode: 'BMD',
        currencyNumber: '060',
        locale: 'en-BM',
    },
    BT: {
        isoAlpha3: 'BTN',
        diallingCode: '975',
        country: 'Bhutan',
        timeZone: 'Asia/Thimphu',
        currencyCode: 'BTN',
        currencyNumber: '064',
        locale: 'dz-BT',
    },
    BO: {
        isoAlpha3: 'BOL',
        diallingCode: '591',
        country: 'Bolivia',
        timeZone: 'America/La_Paz',
        currencyCode: 'BOB',
        currencyNumber: '068',
        locale: 'es-BO',
    },
    BQ: {
        isoAlpha3: 'BES',
        diallingCode: '599',
        country: 'Bonaire, Sint Eustatius and Saba',
        timeZone: 'America/Kralendijk',
        currencyCode: 'USD',
        currencyNumber: '840',
        locale: 'nl-BQ',
    },
    BA: {
        isoAlpha3: 'BIH',
        diallingCode: '387',
        country: 'Bosnia and Herzegovina',
        timeZone: 'Europe/Sarajevo',
        currencyCode: 'BAM',
        currencyNumber: '977',
        locale: 'bs-BA',
    },
    BW: {
        isoAlpha3: 'BWA',
        diallingCode: '267',
        country: 'Botswana',
        timeZone: 'Africa/Gaborone',
        currencyCode: 'BWP',
        currencyNumber: '072',
        locale: 'en-BW',
    },
    BV: {
        isoAlpha3: 'BVT',
        diallingCode: '47',
        country: 'Bouvet Island',
        timeZone: 'Antarctica/Troll',
        locale: '',
    },
    BR: {
        isoAlpha3: 'BRA',
        diallingCode: '55',
        country: 'Brazil',
        timeZone: 'America/Noronha',
        currencyCode: 'BRL',
        currencyNumber: '986',
        locale: 'pt-BR',
    },
    IO: {
        isoAlpha3: 'IOT',
        diallingCode: '246',
        country: 'British Indian Ocean Territory',
        timeZone: 'Indian/Chagos',
        locale: '',
    },
    VG: {
        isoAlpha3: 'VGB',
        diallingCode: '1-284',
        country: 'British Virgin Islands',
        timeZone: 'America/Tortola',
        currencyCode: 'USD',
        currencyNumber: '840',
        locale: 'en-VG',
    },
    BN: {
        isoAlpha3: 'BRN',
        diallingCode: '673',
        country: 'Brunei Darussalam',
        timeZone: 'Asia/Brunei',
        currencyCode: 'BND',
        currencyNumber: '096',
        locale: 'ms-BN',
    },
    BG: {
        isoAlpha3: 'BGR',
        diallingCode: '359',
        country: 'Bulgaria',
        timeZone: 'Europe/Sofia',
        currencyCode: 'BGN',
        currencyNumber: '975',
        locale: 'bg-BG',
    },
    BF: {
        isoAlpha3: 'BFA',
        diallingCode: '226',
        country: 'Burkina Faso',
        timeZone: 'Africa/Ouagadougou',
        currencyCode: 'XOF',
        currencyNumber: '952',
        locale: 'fr-BF',
    },
    BI: {
        isoAlpha3: 'BDI',
        diallingCode: '257',
        country: 'Burundi',
        timeZone: 'Africa/Bujumbura',
        currencyCode: 'BIF',
        currencyNumber: '108',
        locale: 'fr-BI',
    },
    CV: {
        isoAlpha3: 'CPV',
        diallingCode: '238',
        country: 'Cabo Verde',
        timeZone: 'Atlantic/Cape_Verde',
        currencyCode: 'CVE',
        currencyNumber: '132',
        locale: 'pt-CV',
    },
    KH: {
        isoAlpha3: 'KHM',
        diallingCode: '855',
        country: 'Cambodia',
        timeZone: 'Asia/Phnom_Penh',
        currencyCode: 'KHR',
        currencyNumber: '116',
        locale: 'km-KH',
    },
    CM: {
        isoAlpha3: 'CMR',
        diallingCode: '237',
        country: 'Cameroon',
        timeZone: 'Africa/Douala',
        currencyCode: 'XAF',
        currencyNumber: '950',
        locale: 'en-CM',
    },

    CA: {
        isoAlpha3: 'CAN',
        diallingCode: '1',
        country: 'Canada',
        timeZone: 'America/St_Johns',
        currencyCode: 'CAD',
        currencyNumber: '124',
        locale: 'en-CA',
    },
    KY: {
        isoAlpha3: 'CYM',
        diallingCode: '1-345',
        country: 'Cayman Islands',
        timeZone: 'America/Cayman',
        currencyCode: 'KYD',
        currencyNumber: '136',
        locale: 'en-KY',
    },
    CF: {
        isoAlpha3: 'CAF',
        diallingCode: '236',
        country: 'Central African Republic',
        timeZone: 'Africa/Bangui',
        currencyCode: 'XAF',
        currencyNumber: '950',
        locale: 'fr-CF',
    },
    TD: {
        isoAlpha3: 'TCD',
        diallingCode: '235',
        country: 'Chad',
        timeZone: 'Africa/Ndjamena',
        currencyCode: 'XAF',
        currencyNumber: '950',
        locale: 'fr-TD',
    },
    CL: {
        isoAlpha3: 'CHL',
        diallingCode: '56',
        country: 'Chile',
        timeZone: 'America/Santiago',
        currencyCode: 'CLP',
        currencyNumber: '152',
        locale: 'es-CL',
    },
    CN: {
        isoAlpha3: 'CHN',
        diallingCode: '86',
        country: 'China',
        timeZone: 'Asia/Shanghai',
        currencyCode: 'CNY',
        currencyNumber: '156',
        locale: 'zh-CN',
    },
    CX: {
        isoAlpha3: 'CXR',
        diallingCode: '61',
        country: 'Christmas Island',
        timeZone: 'Indian/Christmas',
        locale: '',
    },
    CC: {
        isoAlpha3: 'CCK',
        diallingCode: '61',
        country: 'Cocos (Keeling) Islands',
        timeZone: 'Indian/Cocos',
        locale: '',
    },
    CO: {
        isoAlpha3: 'COL',
        diallingCode: '57',
        country: 'Colombia',
        timeZone: 'America/Bogota',
        currencyCode: 'COP',
        currencyNumber: '170',
        locale: 'es-CO',
    },
    KM: {
        isoAlpha3: 'COM',
        diallingCode: '269',
        country: 'Comoros',
        timeZone: 'Indian/Comoro',
        currencyCode: 'KMF',
        currencyNumber: '174',
        locale: 'fr-KM',
    },
    CG: {
        isoAlpha3: 'COG',
        diallingCode: '242',
        country: 'Congo',
        timeZone: 'Africa/Brazzaville',
        currencyCode: 'XAF',
        currencyNumber: '950',
        locale: 'fr-CG',
    },
    CD: {
        isoAlpha3: 'COD',
        diallingCode: '243',
        country: 'Congo, Democratic Republic of the',
        timeZone: 'Africa/Kinshasa',
        currencyCode: 'CDF',
        currencyNumber: '976',
        locale: 'fr-CD',
    },
    CK: {
        isoAlpha3: 'COK',
        diallingCode: '682',
        country: 'Cook Islands',
        timeZone: 'Pacific/Rarotonga',
        currencyCode: 'NZD',
        currencyNumber: '554',
        locale: 'en-CK',
    },
    CR: {
        isoAlpha3: 'CRI',
        diallingCode: '506',
        country: 'Costa Rica',
        timeZone: 'America/Costa_Rica',
        currencyCode: 'CRC',
        currencyNumber: '188',
        locale: 'es-CR',
    },
    HR: {
        isoAlpha3: 'HRV',
        diallingCode: '385',
        country: 'Croatia',
        timeZone: 'Europe/Zagreb',
        currencyCode: 'HRK',
        currencyNumber: '191',
        locale: 'hr-HR',
    },
    CU: {
        isoAlpha3: 'CUB',
        diallingCode: '53',
        country: 'Cuba',
        timeZone: 'America/Havana',
        currencyCode: 'CUP',
        currencyNumber: '192',
        locale: 'es-CU',
    },
    CW: {
        isoAlpha3: 'CUW',
        diallingCode: '599',
        country: 'Curaçao',
        timeZone: 'America/Curacao',
        currencyCode: 'ANG',
        currencyNumber: '532',
        locale: 'nl-CW',
    },
    CY: {
        isoAlpha3: 'CYP',
        diallingCode: '357',
        country: 'Cyprus',
        timeZone: 'Asia/Nicosia',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'el-CY',
    },
    CZ: {
        isoAlpha3: 'CZE',
        diallingCode: '420',
        country: 'Czech Republic',
        timeZone: 'Europe/Prague',
        currencyCode: 'CZK',
        currencyNumber: '203',
        locale: 'cs-CZ',
    },
    DK: {
        isoAlpha3: 'DNK',
        diallingCode: '45',
        country: 'Denmark',
        timeZone: 'Europe/Copenhagen',
        currencyCode: 'DKK',
        currencyNumber: '208',
        locale: 'da-DK',
    },
    DJ: {
        isoAlpha3: 'DJI',
        diallingCode: '253',
        country: 'Djibouti',
        timeZone: 'Africa/Djibouti',
        currencyCode: 'DJF',
        currencyNumber: '262',
        locale: 'fr-DJ',
    },
    DM: {
        isoAlpha3: 'DMA',
        diallingCode: '1-767',
        country: 'Dominica',
        timeZone: 'America/Dominica',
        currencyCode: 'XCD',
        currencyNumber: '951',
        locale: 'en-DM',
    },
    DO: {
        isoAlpha3: 'DOM',
        diallingCode: '1-809, 1-829, 1-849',
        country: 'Dominican Republic',
        timeZone: 'America/Santo_Domingo',
        currencyCode: 'DOP',
        currencyNumber: '214',
        locale: 'es-DO',
    },
    EC: {
        isoAlpha3: 'ECU',
        diallingCode: '593',
        country: 'Ecuador',
        timeZone: 'America/Guayaquil',
        currencyCode: 'USD',
        currencyNumber: '840',
        locale: 'es-EC',
    },
    EG: {
        isoAlpha3: 'EGY',
        diallingCode: '20',
        country: 'Egypt',
        timeZone: 'Africa/Cairo',
        currencyCode: 'EGP',
        currencyNumber: '818',
        locale: 'ar-EG',
    },
    SV: {
        isoAlpha3: 'SLV',
        diallingCode: '503',
        country: 'El Salvador',
        timeZone: 'America/El_Salvador',
        currencyCode: 'USD',
        currencyNumber: '840',
        locale: 'es-SV',
    },
    GQ: {
        isoAlpha3: 'GNQ',
        diallingCode: '240',
        country: 'Equatorial Guinea',
        timeZone: 'Africa/Malabo',
        currencyCode: 'XAF',
        currencyNumber: '950',
        locale: 'es-GQ',
    },
    ER: {
        isoAlpha3: 'ERI',
        diallingCode: '291',
        country: 'Eritrea',
        timeZone: 'Africa/Asmara',
        currencyCode: 'ERN',
        currencyNumber: '232',
        locale: 'ti-ER',
    },
    EE: {
        isoAlpha3: 'EST',
        diallingCode: '372',
        country: 'Estonia',
        timeZone: 'Europe/Tallinn',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'et-EE',
    },
    ET: {
        isoAlpha3: 'ETH',
        diallingCode: '251',
        country: 'Ethiopia',
        timeZone: 'Africa/Addis_Ababa',
        currencyCode: 'ETB',
        currencyNumber: '230',
        locale: 'am-ET',
    },
    FK: {
        isoAlpha3: 'FLK',
        diallingCode: '500',
        country: 'Falkland Islands (Malvinas)',
        timeZone: 'Atlantic/Stanley',
        currencyCode: 'FKP',
        currencyNumber: '238',
        locale: 'en-FK',
    },
    FO: {
        isoAlpha3: 'FRO',
        diallingCode: '298',
        country: 'Faroe Islands',
        timeZone: 'Atlantic/Faroe',
        currencyCode: 'DKK',
        currencyNumber: '208',
        locale: 'fo-FO',
    },
    FJ: {
        isoAlpha3: 'FJI',
        diallingCode: '679',
        country: 'Fiji',
        timeZone: 'Pacific/Fiji',
        currencyCode: 'FJD',
        currencyNumber: '242',
        locale: 'en-FJ',
    },
    FI: {
        isoAlpha3: 'FIN',
        diallingCode: '358',
        country: 'Finland',
        timeZone: 'Europe/Helsinki',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'fi-FI',
    },
    FR: {
        isoAlpha3: 'FRA',
        diallingCode: '33',
        country: 'France',
        timeZone: 'Europe/Paris',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'fr-FR',
    },
    GF: {
        isoAlpha3: 'GUF',
        diallingCode: '594',
        country: 'French Guiana',
        timeZone: 'America/Cayenne',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'fr-GF',
    },
    PF: {
        isoAlpha3: 'PYF',
        diallingCode: '689',
        country: 'French Polynesia',
        timeZone: 'Pacific/Tahiti',
        currencyCode: 'XPF',
        currencyNumber: '953',
        locale: 'fr-PF',
    },
    TF: {
        isoAlpha3: 'ATF',
        diallingCode: '262',
        country: 'French Southern Territories',
        timeZone: 'Indian/Kerguelen',
        locale: '',
    },
    GA: {
        isoAlpha3: 'GAB',
        diallingCode: '241',
        country: 'Gabon',
        timeZone: 'Africa/Libreville',
        currencyCode: 'XAF',
        currencyNumber: '950',
        locale: 'fr-GA',
    },
    GM: {
        isoAlpha3: 'GMB',
        diallingCode: '220',
        country: 'Gambia',
        timeZone: 'Africa/Banjul',
        currencyCode: 'GMD',
        currencyNumber: '270',
        locale: 'en-GM',
    },
    GE: {
        isoAlpha3: 'GEO',
        diallingCode: '995',
        country: 'Georgia',
        timeZone: 'Asia/Tbilisi',
        currencyCode: 'GEL',
        currencyNumber: '981',
        locale: 'ka-GE',
    },
    DE: {
        isoAlpha3: 'DEU',
        diallingCode: '49',
        country: 'Germany',
        timeZone: 'Europe/Berlin',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'de-DE',
    },
    GH: {
        isoAlpha3: 'GHA',
        diallingCode: '233',
        country: 'Ghana',
        timeZone: 'Africa/Accra',
        currencyCode: 'GHS',
        currencyNumber: '936',
        locale: 'en-GH',
    },
    GI: {
        isoAlpha3: 'GIB',
        diallingCode: '350',
        country: 'Gibraltar',
        timeZone: 'Europe/Gibraltar',
        currencyCode: 'GIP',
        currencyNumber: '292',
        locale: 'en-GI',
    },
    GR: {
        isoAlpha3: 'GRC',
        diallingCode: '30',
        country: 'Greece',
        timeZone: 'Europe/Athens',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'el-GR',
    },
    GL: {
        isoAlpha3: 'GRL',
        diallingCode: '299',
        country: 'Greenland',
        timeZone: 'America/Godthab',
        currencyCode: 'DKK',
        currencyNumber: '208',
        locale: 'kl-GL',
    },
    GD: {
        isoAlpha3: 'GRD',
        diallingCode: '1-473',
        country: 'Grenada',
        timeZone: 'America/Grenada',
        currencyCode: 'XCD',
        currencyNumber: '951',
        locale: 'en-GD',
    },
    GP: {
        isoAlpha3: 'GLP',
        diallingCode: '590',
        country: 'Guadeloupe',
        timeZone: 'America/Guadeloupe',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'fr-GP',
    },
    GU: {
        isoAlpha3: 'GUM',
        diallingCode: '1-671',
        country: 'Guam',
        timeZone: 'Pacific/Guam',
        currencyCode: 'USD',
        currencyNumber: '840',
        locale: 'en-GU',
    },
    GT: {
        isoAlpha3: 'GTM',
        diallingCode: '502',
        country: 'Guatemala',
        timeZone: 'America/Guatemala',
        currencyCode: 'GTQ',
        currencyNumber: '320',
        locale: 'es-GT',
    },
    GG: {
        isoAlpha3: 'GGY',
        diallingCode: '44',
        country: 'Guernsey',
        timeZone: 'Europe/Guernsey',
        currencyCode: 'GBP',
        currencyNumber: '826',
        locale: 'en-GG',
    },
    GN: {
        isoAlpha3: 'GIN',
        diallingCode: '224',
        country: 'Guinea',
        timeZone: 'Africa/Conakry',
        currencyCode: 'GNF',
        currencyNumber: '324',
        locale: 'fr-GN',
    },
    GW: {
        isoAlpha3: 'GNB',
        diallingCode: '245',
        country: 'Guinea-Bissau',
        timeZone: 'Africa/Bissau',
        currencyCode: 'XOF',
        currencyNumber: '952',
        locale: 'pt-GW',
    },
    GY: {
        isoAlpha3: 'GUY',
        diallingCode: '592',
        country: 'Guyana',
        timeZone: 'America/Guyana',
        currencyCode: 'GYD',
        currencyNumber: '328',
        locale: 'en-GY',
    },
    HT: {
        isoAlpha3: 'HTI',
        diallingCode: '509',
        country: 'Haiti',
        timeZone: 'America/Port-au-Prince',
        currencyCode: 'HTG',
        currencyNumber: '332',
        locale: 'fr-HT',
    },
    HM: {
        isoAlpha3: 'HMD',
        diallingCode: '672',
        country: 'Heard Island and McDonald Islands',
        timeZone: 'Indian/Kerguelen',
        locale: '',
    },
    VA: {
        isoAlpha3: 'VAT',
        diallingCode: '379',
        country: 'Holy See (Vatican City State)',
        timeZone: 'Europe/Vatican',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'it-VA',
    },
    HN: {
        isoAlpha3: 'HND',
        diallingCode: '504',
        country: 'Honduras',
        timeZone: 'America/Tegucigalpa',
        currencyCode: 'HNL',
        currencyNumber: '340',
        locale: 'es-HN',
    },
    HK: {
        isoAlpha3: 'HKG',
        diallingCode: '852',
        country: 'Hong Kong',
        timeZone: 'Asia/Hong_Kong',
        currencyCode: 'HKD',
        currencyNumber: '344',
        locale: 'zh-HK',
    },
    HU: {
        isoAlpha3: 'HUN',
        diallingCode: '36',
        country: 'Hungary',
        timeZone: 'Europe/Budapest',
        currencyCode: 'HUF',
        currencyNumber: '348',
        locale: 'hu-HU',
    },
    IS: {
        isoAlpha3: 'ISL',
        diallingCode: '354',
        country: 'Iceland',
        timeZone: 'Atlantic/Reykjavik',
        currencyCode: 'ISK',
        currencyNumber: '352',
        locale: 'is-IS',
    },
    IN: {
        isoAlpha3: 'IND',
        diallingCode: '91',
        country: 'India',
        timeZone: 'Asia/Kolkata',
        currencyCode: 'INR',
        currencyNumber: '356',
        locale: 'hi-IN',
    },
    ID: {
        isoAlpha3: 'IDN',
        diallingCode: '62',
        country: 'Indonesia',
        timeZone: 'Asia/Jakarta',
        currencyCode: 'IDR',
        currencyNumber: '360',
        locale: 'id-ID',
    },
    CI: {
        isoAlpha3: 'CIV',
        diallingCode: '225',
        country: "Côte d'Ivoire",
        timeZone: 'Africa/Abidjan',
        currencyCode: 'XOF',
        currencyNumber: '952',
        locale: 'fr-CI',
    },
    IR: {
        isoAlpha3: 'IRN',
        diallingCode: '98',
        country: 'Iran, Islamic Republic of',
        timeZone: 'Asia/Tehran',
        currencyCode: 'IRR',
        currencyNumber: '364',
        locale: 'fa-IR',
    },
    IQ: {
        isoAlpha3: 'IRQ',
        diallingCode: '964',
        country: 'Iraq',
        timeZone: 'Asia/Baghdad',
        currencyCode: 'IQD',
        currencyNumber: '368',
        locale: 'ar-IQ',
    },
    IE: {
        isoAlpha3: 'IRL',
        diallingCode: '353',
        country: 'Ireland',
        timeZone: 'Europe/Dublin',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'en-IE',
    },
    IM: {
        isoAlpha3: 'IMN',
        diallingCode: '44',
        country: 'Isle of Man',
        timeZone: 'Europe/Isle_of_Man',
        currencyCode: 'GBP',
        currencyNumber: '826',
        locale: 'en-IM',
    },
    IL: {
        isoAlpha3: 'ISR',
        diallingCode: '972',
        country: 'Israel',
        timeZone: 'Asia/Jerusalem',
        currencyCode: 'ILS',
        currencyNumber: '376',
        locale: 'he-IL',
    },
    IT: {
        isoAlpha3: 'ITA',
        diallingCode: '39',
        country: 'Italy',
        timeZone: 'Europe/Rome',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'it-IT',
    },
    JM: {
        isoAlpha3: 'JAM',
        diallingCode: '1-876',
        country: 'Jamaica',
        timeZone: 'America/Jamaica',
        currencyCode: 'JMD',
        currencyNumber: '388',
        locale: 'en-JM',
    },
    JP: {
        isoAlpha3: 'JPN',
        diallingCode: '81',
        country: 'Japan',
        timeZone: 'Asia/Tokyo',
        currencyCode: 'JPY',
        currencyNumber: '392',
        locale: 'ja-JP',
    },
    JE: {
        isoAlpha3: 'JEY',
        diallingCode: '44',
        country: 'Jersey',
        timeZone: 'Europe/Jersey',
        currencyCode: 'GBP',
        currencyNumber: '826',
        locale: 'en-JE',
    },
    JO: {
        isoAlpha3: 'JOR',
        diallingCode: '962',
        country: 'Jordan',
        timeZone: 'Asia/Amman',
        currencyCode: 'JOD',
        currencyNumber: '400',
        locale: 'ar-JO',
    },
    KZ: {
        isoAlpha3: 'KAZ',
        diallingCode: '7',
        country: 'Kazakhstan',
        timeZone: 'Asia/Almaty',
        currencyCode: 'KZT',
        currencyNumber: '398',
        locale: 'kk-KZ',
    },
    KE: {
        isoAlpha3: 'KEN',
        diallingCode: '254',
        country: 'Kenya',
        timeZone: 'Africa/Nairobi',
        currencyCode: 'KES',
        currencyNumber: '404',
        locale: 'sw-KE',
    },
    KI: {
        isoAlpha3: 'KIR',
        diallingCode: '686',
        country: 'Kiribati',
        timeZone: 'Pacific/Tarawa',
        currencyCode: 'AUD',
        currencyNumber: '036',
        locale: 'en-KI',
    },
    KP: {
        isoAlpha3: 'PRK',
        diallingCode: '850',
        country: "Korea, Democratic People's Republic of",
        timeZone: 'Asia/Pyongyang',
        currencyCode: 'KPW',
        currencyNumber: '408',
        locale: 'ko-KP',
    },
    KR: {
        isoAlpha3: 'KOR',
        diallingCode: '82',
        country: 'Korea, Republic of',
        timeZone: 'Asia/Seoul',
        currencyCode: 'KRW',
        currencyNumber: '410',
        locale: 'ko-KR',
    },
    KW: {
        isoAlpha3: 'KWT',
        diallingCode: '965',
        country: 'Kuwait',
        timeZone: 'Asia/Kuwait',
        currencyCode: 'KWD',
        currencyNumber: '414',
        locale: 'ar-KW',
    },
    KG: {
        isoAlpha3: 'KGZ',
        diallingCode: '996',
        country: 'Kyrgyzstan',
        timeZone: 'Asia/Bishkek',
        currencyCode: 'KGS',
        currencyNumber: '417',
        locale: 'ky-KG',
    },
    LA: {
        isoAlpha3: 'LAO',
        diallingCode: '856',
        country: "Lao People's Democratic Republic",
        timeZone: 'Asia/Vientiane',
        currencyCode: 'LAK',
        currencyNumber: '418',
        locale: 'lo-LA',
    },
    LV: {
        isoAlpha3: 'LVA',
        diallingCode: '371',
        country: 'Latvia',
        timeZone: 'Europe/Riga',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'lv-LV',
    },
    LB: {
        isoAlpha3: 'LBN',
        diallingCode: '961',
        country: 'Lebanon',
        timeZone: 'Asia/Beirut',
        currencyCode: 'LBP',
        currencyNumber: '422',
        locale: 'ar-LB',
    },
    LS: {
        isoAlpha3: 'LSO',
        diallingCode: '266',
        country: 'Lesotho',
        timeZone: 'Africa/Maseru',
        currencyCode: 'LSL',
        currencyNumber: '426',
        locale: 'en-LS',
    },
    LR: {
        isoAlpha3: 'LBR',
        diallingCode: '231',
        country: 'Liberia',
        timeZone: 'Africa/Monrovia',
        currencyCode: 'LRD',
        currencyNumber: '430',
        locale: 'en-LR',
    },
    LY: {
        isoAlpha3: 'LBY',
        diallingCode: '218',
        country: 'Libya',
        timeZone: 'Africa/Tripoli',
        currencyCode: 'LYD',
        currencyNumber: '434',
        locale: 'ar-LY',
    },
    LI: {
        isoAlpha3: 'LIE',
        diallingCode: '423',
        country: 'Liechtenstein',
        timeZone: 'Europe/Vaduz',
        currencyCode: 'CHF',
        currencyNumber: '756',
        locale: 'de-LI',
    },
    LT: {
        isoAlpha3: 'LTU',
        diallingCode: '370',
        country: 'Lithuania',
        timeZone: 'Europe/Vilnius',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'lt-LT',
    },
    LU: {
        isoAlpha3: 'LUX',
        diallingCode: '352',
        country: 'Luxembourg',
        timeZone: 'Europe/Luxembourg',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'fr-LU',
    },
    MO: {
        isoAlpha3: 'MAC',
        diallingCode: '853',
        country: 'Macao',
        timeZone: 'Asia/Macau',
        currencyCode: 'MOP',
        currencyNumber: '446',
        locale: 'zh-MO',
    },
    MG: {
        isoAlpha3: 'MDG',
        diallingCode: '261',
        country: 'Madagascar',
        timeZone: 'Indian/Antananarivo',
        currencyCode: 'MGA',
        currencyNumber: '969',
        locale: 'mg-MG',
    },
    MW: {
        isoAlpha3: 'MWI',
        diallingCode: '265',
        country: 'Malawi',
        timeZone: 'Africa/Blantyre',
        currencyCode: 'MWK',
        currencyNumber: '454',
        locale: 'ny-MW',
    },
    MY: {
        isoAlpha3: 'MYS',
        diallingCode: '60',
        country: 'Malaysia',
        timeZone: 'Asia/Kuala_Lumpur',
        currencyCode: 'MYR',
        currencyNumber: '458',
        locale: 'ms-MY',
    },
    MV: {
        isoAlpha3: 'MDV',
        diallingCode: '960',
        country: 'Maldives',
        timeZone: 'Indian/Maldives',
        currencyCode: 'MVR',
        currencyNumber: '462',
        locale: 'dv-MV',
    },
    ML: {
        isoAlpha3: 'MLI',
        diallingCode: '223',
        country: 'Mali',
        timeZone: 'Africa/Bamako',
        currencyCode: 'XOF',
        currencyNumber: '952',
        locale: 'fr-ML',
    },
    MT: {
        isoAlpha3: 'MLT',
        diallingCode: '356',
        country: 'Malta',
        timeZone: 'Europe/Malta',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'mt-MT',
    },
    MH: {
        isoAlpha3: 'MHL',
        diallingCode: '692',
        country: 'Marshall Islands',
        timeZone: 'Pacific/Majuro',
        currencyCode: 'USD',
        currencyNumber: '840',
        locale: 'en-MH',
    },
    MQ: {
        isoAlpha3: 'MTQ',
        diallingCode: '596',
        country: 'Martinique',
        timeZone: 'America/Martinique',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'fr-MQ',
    },
    MR: {
        isoAlpha3: 'MRT',
        diallingCode: '222',
        country: 'Mauritania',
        timeZone: 'Africa/Nouakchott',
        currencyCode: 'MRO',
        currencyNumber: '478',
        locale: 'ar-MR',
    },
    MU: {
        isoAlpha3: 'MUS',
        diallingCode: '230',
        country: 'Mauritius',
        timeZone: 'Indian/Mauritius',
        currencyCode: 'MUR',
        currencyNumber: '480',
        locale: 'en-MU',
    },
    YT: {
        isoAlpha3: 'MYT',
        diallingCode: '262',
        country: 'Mayotte',
        timeZone: 'Indian/Mayotte',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'fr-YT',
    },
    MX: {
        isoAlpha3: 'MEX',
        diallingCode: '52',
        country: 'Mexico',
        timeZone: 'America/Mexico_City',
        currencyCode: 'MXN',
        currencyNumber: '484',
        locale: 'es-MX',
    },
    FM: {
        isoAlpha3: 'FSM',
        diallingCode: '691',
        country: 'Micronesia, Federated States of',
        timeZone: 'Pacific/Chuuk',
        currencyCode: 'USD',
        currencyNumber: '840',
        locale: 'en-FM',
    },
    MD: {
        isoAlpha3: 'MDA',
        diallingCode: '373',
        country: 'Moldova, Republic of',
        timeZone: 'Europe/Chisinau',
        currencyCode: 'MDL',
        currencyNumber: '498',
        locale: 'ro-MD',
    },
    MC: {
        isoAlpha3: 'MCO',
        diallingCode: '377',
        country: 'Monaco',
        timeZone: 'Europe/Monaco',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'fr-MC',
    },
    MN: {
        isoAlpha3: 'MNG',
        diallingCode: '976',
        country: 'Mongolia',
        timeZone: 'Asia/Ulaanbaatar',
        currencyCode: 'MNT',
        currencyNumber: '496',
        locale: 'mn-MN',
    },
    ME: {
        isoAlpha3: 'MNE',
        diallingCode: '382',
        country: 'Montenegro',
        timeZone: 'Europe/Podgorica',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'sr-ME',
    },
    MS: {
        isoAlpha3: 'MSR',
        diallingCode: '1-664',
        country: 'Montserrat',
        timeZone: 'America/Montserrat',
        currencyCode: 'XCD',
        currencyNumber: '951',
        locale: 'en-MS',
    },
    MA: {
        isoAlpha3: 'MAR',
        diallingCode: '212',
        country: 'Morocco',
        timeZone: 'Africa/Casablanca',
        currencyCode: 'MAD',
        currencyNumber: '504',
        locale: 'ar-MA',
    },
    MZ: {
        isoAlpha3: 'MOZ',
        diallingCode: '258',
        country: 'Mozambique',
        timeZone: 'Africa/Maputo',
        currencyCode: 'MZN',
        currencyNumber: '943',
        locale: 'pt-MZ',
    },
    MM: {
        isoAlpha3: 'MMR',
        diallingCode: '95',
        country: 'Myanmar',
        timeZone: 'Asia/Yangon',
        currencyCode: 'MMK',
        currencyNumber: '104',
        locale: 'my-MM',
    },
    NA: {
        isoAlpha3: 'NAM',
        diallingCode: '264',
        country: 'Namibia',
        timeZone: 'Africa/Windhoek',
        currencyCode: 'NAD',
        currencyNumber: '516',
        locale: 'en-NA',
    },
    NR: {
        isoAlpha3: 'NRU',
        diallingCode: '674',
        country: 'Nauru',
        timeZone: 'Pacific/Nauru',
        currencyCode: 'AUD',
        currencyNumber: '036',
        locale: 'na-NR',
    },
    NP: {
        isoAlpha3: 'NPL',
        diallingCode: '977',
        country: 'Nepal',
        timeZone: 'Asia/Kathmandu',
        currencyCode: 'NPR',
        currencyNumber: '524',
        locale: 'ne-NP',
    },
    NL: {
        isoAlpha3: 'NLD',
        diallingCode: '31',
        country: 'Netherlands',
        timeZone: 'Europe/Amsterdam',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'nl-NL',
    },
    NC: {
        isoAlpha3: 'NCL',
        diallingCode: '687',
        country: 'New Caledonia',
        timeZone: 'Pacific/Noumea',
        currencyCode: 'XPF',
        currencyNumber: '953',
        locale: 'fr-NC',
    },
    NZ: {
        isoAlpha3: 'NZL',
        diallingCode: '64',
        country: 'New Zealand',
        timeZone: 'Pacific/Auckland',
        currencyCode: 'NZD',
        currencyNumber: '554',
        locale: 'en-NZ',
    },
    NI: {
        isoAlpha3: 'NIC',
        diallingCode: '505',
        country: 'Nicaragua',
        timeZone: 'America/Managua',
        currencyCode: 'NIO',
        currencyNumber: '558',
        locale: 'es-NI',
    },
    NE: {
        isoAlpha3: 'NER',
        diallingCode: '227',
        country: 'Niger',
        timeZone: 'Africa/Niamey',
        currencyCode: 'XOF',
        currencyNumber: '952',
        locale: 'fr-NE',
    },
    NG: {
        isoAlpha3: 'NGA',
        diallingCode: '234',
        country: 'Nigeria',
        timeZone: 'Africa/Lagos',
        currencyCode: 'NGN',
        currencyNumber: '566',
        locale: 'en-NG',
    },
    NU: {
        isoAlpha3: 'NIU',
        diallingCode: '683',
        country: 'Niue',
        timeZone: 'Pacific/Niue',
        currencyCode: 'NZD',
        currencyNumber: '554',
        locale: 'niu',
    },
    NF: {
        isoAlpha3: 'NFK',
        diallingCode: '672',
        country: 'Norfolk Island',
        timeZone: 'Pacific/Norfolk',
        locale: '',
    },
    MK: {
        isoAlpha3: 'MKD',
        diallingCode: '389',
        country: 'North Macedonia',
        timeZone: 'Europe/Skopje',
        currencyCode: 'MKD',
        currencyNumber: '807',
        locale: 'mk-MK',
    },
    MP: {
        isoAlpha3: 'MNP',
        diallingCode: '1-670',
        country: 'Northern Mariana Islands',
        timeZone: 'Pacific/Saipan',
        currencyCode: 'USD',
        currencyNumber: '840',
        locale: 'en-MP',
    },
    NO: {
        isoAlpha3: 'NOR',
        diallingCode: '47',
        country: 'Norway',
        timeZone: 'Europe/Oslo',
        currencyCode: 'NOK',
        currencyNumber: '578',
        locale: 'nb-NO',
    },
    OM: {
        isoAlpha3: 'OMN',
        diallingCode: '968',
        country: 'Oman',
        timeZone: 'Asia/Muscat',
        currencyCode: 'OMR',
        currencyNumber: '512',
        locale: 'ar-OM',
    },
    PK: {
        isoAlpha3: 'PAK',
        diallingCode: '92',
        country: 'Pakistan',
        timeZone: 'Asia/Karachi',
        currencyCode: 'PKR',
        currencyNumber: '586',
        locale: 'ur-PK',
    },
    PW: {
        isoAlpha3: 'PLW',
        diallingCode: '680',
        country: 'Palau',
        timeZone: 'Pacific/Palau',
        currencyCode: 'USD',
        currencyNumber: '840',
        locale: 'en-PW',
    },
    PS: {
        isoAlpha3: 'PSE',
        diallingCode: '970',
        country: 'Palestine, State of',
        timeZone: 'Asia/Gaza',
        currencyCode: 'ILS',
        currencyNumber: '376',
        locale: 'ar-PS',
    },
    PA: {
        isoAlpha3: 'PAN',
        diallingCode: '507',
        country: 'Panama',
        timeZone: 'America/Panama',
        currencyCode: 'PAB',
        currencyNumber: '590',
        locale: 'es-PA',
    },
    PG: {
        isoAlpha3: 'PNG',
        diallingCode: '675',
        country: 'Papua New Guinea',
        timeZone: 'Pacific/Port_Moresby',
        currencyCode: 'PGK',
        currencyNumber: '598',
        locale: 'en-PG',
    },
    PY: {
        isoAlpha3: 'PRY',
        diallingCode: '595',
        country: 'Paraguay',
        timeZone: 'America/Asuncion',
        currencyCode: 'PYG',
        currencyNumber: '600',
        locale: 'es-PY',
    },
    PE: {
        isoAlpha3: 'PER',
        diallingCode: '51',
        country: 'Peru',
        timeZone: 'America/Lima',
        currencyCode: 'PEN',
        currencyNumber: '604',
        locale: 'es-PE',
    },
    PH: {
        isoAlpha3: 'PHL',
        diallingCode: '63',
        country: 'Philippines',
        timeZone: 'Asia/Manila',
        currencyCode: 'PHP',
        currencyNumber: '608',
        locale: 'fil-PH',
    },
    PN: {
        isoAlpha3: 'PCN',
        diallingCode: '64',
        country: 'Pitcairn',
        timeZone: 'Pacific/Pitcairn',
        locale: '',
    },
    PL: {
        isoAlpha3: 'POL',
        diallingCode: '48',
        country: 'Poland',
        timeZone: 'Europe/Warsaw',
        currencyCode: 'PLN',
        currencyNumber: '985',
        locale: 'pl-PL',
    },
    PT: {
        isoAlpha3: 'PRT',
        diallingCode: '351',
        country: 'Portugal',
        timeZone: 'Europe/Lisbon',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'pt-PT',
    },
    PR: {
        isoAlpha3: 'PRI',
        diallingCode: '1-787',
        country: 'Puerto Rico',
        timeZone: 'America/Puerto_Rico',
        currencyCode: 'USD',
        currencyNumber: '840',
        locale: 'es-PR',
    },
    QA: {
        isoAlpha3: 'QAT',
        diallingCode: '974',
        country: 'Qatar',
        timeZone: 'Asia/Qatar',
        currencyCode: 'QAR',
        currencyNumber: '634',
        locale: 'ar-QA',
    },
    RE: {
        isoAlpha3: 'REU',
        diallingCode: '262',
        country: 'Réunion',
        timeZone: 'Indian/Reunion',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'fr-RE',
    },
    RO: {
        isoAlpha3: 'ROU',
        diallingCode: '40',
        country: 'Romania',
        timeZone: 'Europe/Bucharest',
        currencyCode: 'RON',
        currencyNumber: '946',
        locale: 'ro-RO',
    },
    RU: {
        isoAlpha3: 'RUS',
        diallingCode: '7',
        country: 'Russian Federation',
        timeZone: 'Europe/Moscow',
        currencyCode: 'RUB',
        currencyNumber: '643',
        locale: 'ru-RU',
    },
    RW: {
        isoAlpha3: 'RWA',
        diallingCode: '250',
        country: 'Rwanda',
        timeZone: 'Africa/Kigali',
        currencyCode: 'RWF',
        currencyNumber: '646',
        locale: 'rw-RW',
    },
    BL: {
        isoAlpha3: 'BLM',
        diallingCode: '590',
        country: 'Saint Barthélemy',
        timeZone: 'America/St_Barthelemy',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'fr-BL',
    },
    SH: {
        isoAlpha3: 'SHN',
        diallingCode: '290',
        country: 'Saint Helena, Ascension and Tristan da Cunha',
        timeZone: 'Atlantic/St_Helena',
        currencyCode: 'SHP',
        currencyNumber: '654',
        locale: 'en-SH',
    },
    KN: {
        isoAlpha3: 'KNA',
        diallingCode: '1-869',
        country: 'Saint Kitts and Nevis',
        timeZone: 'America/St_Kitts',
        currencyCode: 'XCD',
        currencyNumber: '951',
        locale: 'en-KN',
    },
    LC: {
        isoAlpha3: 'LCA',
        diallingCode: '1-758',
        country: 'Saint Lucia',
        timeZone: 'America/St_Lucia',
        currencyCode: 'XCD',
        currencyNumber: '951',
        locale: 'en-LC',
    },
    MF: {
        isoAlpha3: 'MAF',
        diallingCode: '590',
        country: 'Saint Martin (French part)',
        timeZone: 'America/Marigot',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'fr-MF',
    },
    PM: {
        isoAlpha3: 'SPM',
        diallingCode: '508',
        country: 'Saint Pierre and Miquelon',
        timeZone: 'America/Miquelon',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'fr-PM',
    },
    VC: {
        isoAlpha3: 'VCT',
        diallingCode: '1-784',
        country: 'Saint Vincent and the Grenadines',
        timeZone: 'America/St_Vincent',
        currencyCode: 'XCD',
        currencyNumber: '951',
        locale: 'en-VC',
    },
    WS: {
        isoAlpha3: 'WSM',
        diallingCode: '685',
        country: 'Samoa',
        timeZone: 'Pacific/Apia',
        currencyCode: 'WST',
        currencyNumber: '882',
        locale: 'sm',
    },
    SM: {
        isoAlpha3: 'SMR',
        diallingCode: '378',
        country: 'San Marino',
        timeZone: 'Europe/San_Marino',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'it-SM',
    },
    ST: {
        isoAlpha3: 'STP',
        diallingCode: '239',
        country: 'Sao Tome and Principe',
        timeZone: 'Africa/Sao_Tome',
        currencyCode: 'STN',
        currencyNumber: '930',
        locale: 'pt-ST',
    },
    SA: {
        isoAlpha3: 'SAU',
        diallingCode: '966',
        country: 'Saudi Arabia',
        timeZone: 'Asia/Riyadh',
        currencyCode: 'SAR',
        currencyNumber: '682',
        locale: 'ar-SA',
    },
    SN: {
        isoAlpha3: 'SEN',
        diallingCode: '221',
        country: 'Senegal',
        timeZone: 'Africa/Dakar',
        currencyCode: 'XOF',
        currencyNumber: '952',
        locale: 'fr-SN',
    },
    RS: {
        isoAlpha3: 'SRB',
        diallingCode: '381',
        country: 'Serbia',
        timeZone: 'Europe/Belgrade',
        currencyCode: 'RSD',
        currencyNumber: '941',
        locale: 'sr-RS',
    },
    SC: {
        isoAlpha3: 'SYC',
        diallingCode: '248',
        country: 'Seychelles',
        timeZone: 'Indian/Mahe',
        currencyCode: 'SCR',
        currencyNumber: '690',
        locale: 'en-SC',
    },
    SL: {
        isoAlpha3: 'SLE',
        diallingCode: '232',
        country: 'Sierra Leone',
        timeZone: 'Africa/Freetown',
        currencyCode: 'SLL',
        currencyNumber: '694',
        locale: 'en-SL',
    },
    SG: {
        isoAlpha3: 'SGP',
        diallingCode: '65',
        country: 'Singapore',
        timeZone: 'Asia/Singapore',
        currencyCode: 'SGD',
        currencyNumber: '702',
        locale: 'zh-SG',
    },
    SX: {
        isoAlpha3: 'SXM',
        diallingCode: '1-721',
        country: 'Sint Maarten (Dutch part)',
        timeZone: 'America/Lower_Princes',
        currencyCode: 'ANG',
        currencyNumber: '532',
        locale: 'nl-SX',
    },
    SK: {
        isoAlpha3: 'SVK',
        diallingCode: '421',
        country: 'Slovakia',
        timeZone: 'Europe/Bratislava',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'sk-SK',
    },
    SI: {
        isoAlpha3: 'SVN',
        diallingCode: '386',
        country: 'Slovenia',
        timeZone: 'Europe/Ljubljana',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'sl-SI',
    },
    SB: {
        isoAlpha3: 'SLB',
        diallingCode: '677',
        country: 'Solomon Islands',
        timeZone: 'Pacific/Guadalcanal',
        currencyCode: 'SBD',
        currencyNumber: '090',
        locale: 'en-SB',
    },
    SO: {
        isoAlpha3: 'SOM',
        diallingCode: '252',
        country: 'Somalia',
        timeZone: 'Africa/Mogadishu',
        currencyCode: 'SOS',
        currencyNumber: '706',
        locale: 'so-SO',
    },
    ZA: {
        isoAlpha3: 'ZAF',
        diallingCode: '27',
        country: 'South Africa',
        timeZone: 'Africa/Johannesburg',
        currencyCode: 'ZAR',
        currencyNumber: '710',
        locale: 'en-ZA',
    },
    GS: {
        isoAlpha3: 'SGS',
        diallingCode: '500',
        country: 'South Georgia and the South Sandwich Islands',
        timeZone: 'Atlantic/South_Georgia',
        currencyCode: 'GBP',
        currencyNumber: '826',
        locale: '',
    },
    SS: {
        isoAlpha3: 'SSD',
        diallingCode: '211',
        country: 'South Sudan',
        timeZone: 'Africa/Juba',
        currencyCode: 'SSP',
        currencyNumber: '728',
        locale: 'en-SS',
    },
    ES: {
        isoAlpha3: 'ESP',
        diallingCode: '34',
        country: 'Spain',
        timeZone: 'Europe/Madrid',
        currencyCode: 'EUR',
        currencyNumber: '978',
        locale: 'es-ES',
    },
    LK: {
        isoAlpha3: 'LKA',
        diallingCode: '94',
        country: 'Sri Lanka',
        timeZone: 'Asia/Colombo',
        currencyCode: 'LKR',
        currencyNumber: '144',
        locale: 'si-LK',
    },
    SD: {
        isoAlpha3: 'SDN',
        diallingCode: '249',
        country: 'Sudan',
        timeZone: 'Africa/Khartoum',
        currencyCode: 'SDG',
        currencyNumber: '938',
        locale: 'ar-SD',
    },
    SR: {
        isoAlpha3: 'SUR',
        diallingCode: '597',
        country: 'Suriname',
        timeZone: 'America/Paramaribo',
        currencyCode: 'SRD',
        currencyNumber: '968',
        locale: 'nl-SR',
    },
    SJ: {
        isoAlpha3: 'SJM',
        diallingCode: '47',
        country: 'Svalbard and Jan Mayen',
        timeZone: 'Arctic/Longyearbyen',
        locale: '',
    },
    SE: {
        isoAlpha3: 'SWE',
        diallingCode: '46',
        country: 'Sweden',
        timeZone: 'Europe/Stockholm',
        currencyCode: 'SEK',
        currencyNumber: '752',
        locale: 'sv-SE',
    },
    CH: {
        isoAlpha3: 'CHE',
        diallingCode: '41',
        country: 'Switzerland',
        timeZone: 'Europe/Zurich',
        currencyCode: 'CHF',
        currencyNumber: '756',
        locale: 'de-CH',
    },
    SY: {
        isoAlpha3: 'SYR',
        diallingCode: '963',
        country: 'Syrian Arab Republic',
        timeZone: 'Asia/Damascus',
        currencyCode: 'SYP',
        currencyNumber: '760',
        locale: 'ar-SY',
    },
    TW: {
        isoAlpha3: 'TWN',
        diallingCode: '886',
        country: 'Taiwan, Province of China',
        timeZone: 'Asia/Taipei',
        currencyCode: 'TWD',
        currencyNumber: '901',
        locale: 'zh-TW',
    },
    TJ: {
        isoAlpha3: 'TJK',
        diallingCode: '992',
        country: 'Tajikistan',
        timeZone: 'Asia/Dushanbe',
        currencyCode: 'TJS',
        currencyNumber: '972',
        locale: 'tg-TJ',
    },
    TZ: {
        isoAlpha3: 'TZA',
        diallingCode: '255',
        country: 'Tanzania, United Republic of',
        timeZone: 'Africa/Dar_es_Salaam',
        currencyCode: 'TZS',
        currencyNumber: '834',
        locale: 'sw-TZ',
    },
    TH: {
        isoAlpha3: 'THA',
        diallingCode: '66',
        country: 'Thailand',
        timeZone: 'Asia/Bangkok',
        currencyCode: 'THB',
        currencyNumber: '764',
        locale: 'th-TH',
    },
    TL: {
        isoAlpha3: 'TLS',
        diallingCode: '670',
        country: 'Timor-Leste',
        timeZone: 'Asia/Dili',
        currencyCode: 'USD',
        currencyNumber: '840',
        locale: 'tet',
    },
    TG: {
        isoAlpha3: 'TGO',
        diallingCode: '228',
        country: 'Togo',
        timeZone: 'Africa/Lome',
        currencyCode: 'XOF',
        currencyNumber: '952',
        locale: 'fr-TG',
    },
    TK: {
        isoAlpha3: 'TKL',
        diallingCode: '690',
        country: 'Tokelau',
        timeZone: 'Pacific/Fakaofo',
        locale: '',
    },
    TO: {
        isoAlpha3: 'TON',
        diallingCode: '676',
        country: 'Tonga',
        timeZone: 'Pacific/Tongatapu',
        currencyCode: 'TOP',
        currencyNumber: '776',
        locale: 'to-TO',
    },
    TT: {
        isoAlpha3: 'TTO',
        diallingCode: '1-868',
        country: 'Trinidad and Tobago',
        timeZone: 'America/Port_of_Spain',
        currencyCode: 'TTD',
        currencyNumber: '780',
        locale: 'en-TT',
    },
    TN: {
        isoAlpha3: 'TUN',
        diallingCode: '216',
        country: 'Tunisia',
        timeZone: 'Africa/Tunis',
        currencyCode: 'TND',
        currencyNumber: '788',
        locale: 'ar-TN',
    },
    TR: {
        isoAlpha3: 'TUR',
        diallingCode: '90',
        country: 'Turkey',
        timeZone: 'Europe/Istanbul',
        currencyCode: 'TRY',
        currencyNumber: '949',
        locale: 'tr-TR',
    },
    TM: {
        isoAlpha3: 'TKM',
        diallingCode: '993',
        country: 'Turkmenistan',
        timeZone: 'Asia/Ashgabat',
        currencyCode: 'TMT',
        currencyNumber: '934',
        locale: 'tk-TM',
    },
    TC: {
        isoAlpha3: 'TCA',
        diallingCode: '1-649',
        country: 'Turks and Caicos Islands',
        timeZone: 'America/Grand_Turk',
        currencyCode: 'USD',
        currencyNumber: '840',
        locale: 'en-TC',
    },
    TV: {
        isoAlpha3: 'TUV',
        diallingCode: '688',
        country: 'Tuvalu',
        timeZone: 'Pacific/Funafuti',
        currencyCode: 'AUD',
        currencyNumber: '036',
        locale: 'tvl',
    },
    UG: {
        isoAlpha3: 'UGA',
        diallingCode: '256',
        country: 'Uganda',
        timeZone: 'Africa/Kampala',
        currencyCode: 'UGX',
        currencyNumber: '800',
        locale: 'en-UG',
    },
    UA: {
        isoAlpha3: 'UKR',
        diallingCode: '380',
        country: 'Ukraine',
        timeZone: 'Europe/Kiev',
        currencyCode: 'UAH',
        currencyNumber: '980',
        locale: 'uk-UA',
    },
    AE: {
        isoAlpha3: 'ARE',
        diallingCode: '971',
        country: 'United Arab Emirates',
        timeZone: 'Asia/Dubai',
        currencyCode: 'AED',
        currencyNumber: '784',
        locale: 'ar-AE',
    },
    GB: {
        isoAlpha3: 'GBR',
        diallingCode: '44',
        country: 'United Kingdom',
        timeZone: 'Europe/London',
        currencyCode: 'GBP',
        currencyNumber: '826',
        locale: 'en-GB',
    },
    UK: {
        isoAlpha3: 'GBR',
        diallingCode: '44',
        country: 'United Kingdom',
        timeZone: 'Europe/London',
        currencyCode: 'GBP',
        currencyNumber: '826',
        locale: 'en-GB',
    },
    US: {
        isoAlpha3: 'USA',
        diallingCode: '1',
        country: 'United States',
        timeZone: 'America/New_York',
        currencyCode: 'USD',
        currencyNumber: '840',
        locale: 'en-US',
    },
    UM: {
        isoAlpha3: 'UMI',
        diallingCode: '1',
        country: 'United States Minor Outlying Islands',
        timeZone: 'Pacific/Midway',
        locale: '',
    },
    UY: {
        isoAlpha3: 'URY',
        diallingCode: '598',
        country: 'Uruguay',
        timeZone: 'America/Montevideo',
        currencyCode: 'UYU',
        currencyNumber: '858',
        locale: 'es-UY',
    },
    UZ: {
        isoAlpha3: 'UZB',
        diallingCode: '998',
        country: 'Uzbekistan',
        timeZone: 'Asia/Samarkand',
        currencyCode: 'UZS',
        currencyNumber: '860',
        locale: 'uz-UZ',
    },
    VU: {
        isoAlpha3: 'VUT',
        diallingCode: '678',
        country: 'Vanuatu',
        timeZone: 'Pacific/Efate',
        currencyCode: 'VUV',
        currencyNumber: '548',
        locale: 'bi-VU',
    },
    VE: {
        isoAlpha3: 'VEN',
        diallingCode: '58',
        country: 'Venezuela, Bolivarian Republic of',
        timeZone: 'America/Caracas',
        currencyCode: 'VES',
        currencyNumber: '928',
        locale: 'es-VE',
    },
    VN: {
        isoAlpha3: 'VNM',
        diallingCode: '84',
        country: 'Viet Nam',
        timeZone: 'Asia/Ho_Chi_Minh',
        currencyCode: 'VND',
        currencyNumber: '704',
        locale: 'vi-VN',
    },
    VI: {
        isoAlpha3: 'VIR',
        diallingCode: '1-340',
        country: 'Virgin Islands, U.S.',
        timeZone: 'America/St_Thomas',
        currencyCode: 'USD',
        currencyNumber: '840',
        locale: 'en-VI',
    },
    WF: {
        isoAlpha3: 'WLF',
        diallingCode: '681',
        country: 'Wallis and Futuna',
        timeZone: 'Pacific/Wallis',
        currencyCode: 'XPF',
        currencyNumber: '953',
        locale: 'fr-WF',
    },
    EH: {
        isoAlpha3: 'ESH',
        diallingCode: '212',
        country: 'Western Sahara',
        timeZone: 'Africa/El_Aaiun',
        currencyCode: 'MAD',
        currencyNumber: '504',
        locale: 'ar',
    },
    YE: {
        isoAlpha3: 'YEM',
        diallingCode: '967',
        country: 'Yemen',
        timeZone: 'Asia/Aden',
        currencyCode: 'YER',
        currencyNumber: '886',
        locale: 'ar-YE',
    },
    ZM: {
        isoAlpha3: 'ZMB',
        diallingCode: '260',
        country: 'Zambia',
        timeZone: 'Africa/Lusaka',
        currencyCode: 'ZMW',
        currencyNumber: '967',
        locale: 'en-ZM',
    },
    ZW: {
        isoAlpha3: 'ZWE',
        diallingCode: '263',
        country: 'Zimbabwe',
        timeZone: 'Africa/Harare',
        currencyCode: 'ZWL',
        currencyNumber: '932',
        locale: 'en-ZW',
    },
    default: {
        isoAlpha3: 'SWE',
        diallingCode: '46',
        country: 'Sweden',
        timeZone: 'Europe/Stockholm',
        currencyCode: 'SEK',
        currencyNumber: '752',
        locale: 'sv-SE',
    },
} as const;
